"""Qwen policy wrapper (v0 heuristic stub)."""

from __future__ import annotations

from dataclasses import dataclass

from kite.types import KernelCandidate, KernelTask


@dataclass(slots=True)
class QwenPolicyConfig:
    model_name: str = "Qwen/Qwen2.5-Coder-7B-Instruct"
    temperature: float = 0.8
    max_new_tokens: int = 1024


class QwenPolicy:
    """Policy facade for kernel generation.

    This v0 implementation is deterministic and model-free to keep local tests
    lightweight. Replace `generate_candidate` with real model inference.
    """

    def __init__(self, config: QwenPolicyConfig | None = None) -> None:
        self.config = config or QwenPolicyConfig()

    def generate_candidate(self, task: KernelTask, attempt: int = 0) -> KernelCandidate:
        compile_ok = attempt % 5 != 0
        correct = compile_ok and attempt % 3 != 0

        code = (
            "def kernel(*args, **kwargs):\n"
            "    # generated by qwen policy stub\n"
            f"    # task={task.task_id} attempt={attempt}\n"
        )
        if not compile_ok:
            code += "    TODO\n"
        elif correct:
            code += "    return args[0] if args else None\n"
        else:
            code += "    return None\n"

        runtime_ms = 75.0 + float((attempt % 7) * 5)
        speedup = max(0.2, 100.0 / runtime_ms)

        return KernelCandidate(
            task_id=task.task_id,
            code=code,
            compile_ok=compile_ok,
            correct=correct,
            runtime_ms=runtime_ms,
            speedup=speedup,
            logs={"policy": self.config.model_name, "attempt": attempt},
        )
